LOG_LEVEL = 'ERROR'
LOG_ENABLED = True
LOG_ENCODING = 'utf-8'
LOG_FORMATTER = 'agent_spider.log_formatter.SilentLogFormatter'
LOG_FORMAT = '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
LOG_DATEFORMAT = '%Y-%m-%d %H:%M:%S'
LOG_STDOUT = False
LOG_FILE = None
LOG_SHORT_NAMES = False